### ISSUE TITLE
show() in scikitlearnAPI.jl write to standard out instead of io stream

### ISSUE THREAD

**Issue by kvantitative** [bensadeghi/DecisionTree.jl#103]
The function show is used to print out the decision trees. It takes a IO stream as a input, and write out the decision tree to this input. The IO stream is argument io to the function.

However, some of the output is written to the standard output instead of to the IO stream. Normally this is not an big issue, since the IO stream is pointing to standard output anyway, but when you uses the Juno IDE the output is messed up.

The function show is found in line 76-86 in scikitlearnAPI.jl, in v 0.8.3. Line 84-85 is:
print(io,   "classes:                  ") ; show(dt.classes) ; println()
print(io,   "root:                     ") ; show(dt.root)

but should be:
print(io,   "classes:                  ") ; show(io,dt.classes) ; println(io,"")
print(io,   "root:                     ") ; show(io,dt.root)

**Comment by bensadeghi** [comment]
@JuliaRegistrator register

**Comment by bensadeghi** [comment]
@kvantitative 
Thanks for catching this. I think the issue should be resolved now
Please give it a test try once v0.8.4 is available in the package registry (in a day or so)

**Comment by kvantitative** [comment]
Hi bensadeghi,
Looks fine to me! - and thanks for a great package.
