### ISSUE TITLE
Fit Decision Tree with given Structure

### ISSUE THREAD

**Issue by modedec** [bensadeghi/DecisionTree.jl#106]
Is it possible to Fit a Decision Tree with a given structure? If so, is there an example?

Thx for any hint

**Comment by bensadeghi** [comment]
The features space and thresholds to split on are searched for you, and the most optimal splits (measured by information gain, ie Shannon entropy) are used to generate the structure of the tree.
There is no option to fit the feature/threshold splits to a given structure.
