### ISSUE TITLE
Multi-output random forest regression

### ISSUE THREAD

**Issue by bielim** [bensadeghi/DecisionTree.jl#117]
Python's `scikit-learn` library can fit multi-output random forest regression models (multi-output meaning that the targets/outputs are multi-valued):
```
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

# Generate synthetic dataset
X, y = make_regression(n_samples=1000, n_features=10, n_informative=5, n_targets=2)
# Fit random forest regression model
model = RandomForestRegressor(max_depth=5, n_estimators=10)
model.fit(X, y)
```
The `RandomForestRegressor` in `DecisionTree.jl` doesn't seem to be able to deal with multi-valued targets: 
```
using DecisionTree

model = RandomForestRegressor(n_trees=10, max_depth=5)
fit!(model, X, y)
```
This gives a `MethodError: no method matching fit!(::RandomForestRegressor, ::Array{Float64,2}, ::Array{Float64,2})`.

Is there a way to do multi-output random forest regression using `DecisionTree.jl` (or any other Julia package)?

**Comment by bensadeghi** [comment]
Multi-output classification/regression are not supported by this package.
You can check with the greater [Julia community](https://julialang.org/community/) about which packages do provide such functionality.
