### ISSUE TITLE
Features of type AbstractVector in apply_tree?

### ISSUE THREAD

**Issue by barucden** [bensadeghi/DecisionTree.jl#124]
Hi. Is there any particular reason why the prediction (`apply_tree`) supports features of type `Vector` only? As far as I can tell, `AbstractVector` should deliver all the functionality (i.e., indexing) we need here. Or am I missing something? Thanks.

Edit: AbstractVector would allow us to pass, e.g., Views to the function.

**Comment by bensadeghi** [comment]
Resolved with #128
