### ISSUE TITLE
Facing issues with build_adaboost_stumps

### ISSUE THREAD

**Issue by dgmattam** [bensadeghi/DecisionTree.jl#18]
I have used the adaboost function multiple times earlier, but now it throws the following error.  

ERROR: DomainError
 in build_adaboost_stumps at C:\Users\Dinkar\.julia\v0.3\DecisionTree\src\Decisi
onTree.jl:281

I tried going step by step and found that the function on line 280 of the  DecisionTree.jl/src/DecisionTree.jl (reproduced below) was not working. 

 err = _weighted_error(labels, predictions, weights)

It would be great if you could guide me on how to proceed. 

Thank you
Dinker

**Comment by bensadeghi** [comment]
My simple tests on the adaboost function are still passing.
Could you provide me with more info, like the error trace, or better yet, a way for me to reproduce the error?
btw, you might be better off using random forests; they typically provide higher precision and are faster.
