### ISSUE TITLE
minimum size of each leaf

### ISSUE THREAD

**Issue by veryluckyxyz** [bensadeghi/DecisionTree.jl#21]
Hi, is there a way to limit size of a leaf to prevent overfitting? Something similar to `minbucket` in R?

Thanks a lot for sharing your code!

**Comment by bensadeghi** [comment]
For regression purposes, overfitting is remedied by increasing the maximum number of samples allowed per leaf (default = 5): ```model = build_tree(labels, features, max_samples_per_leaf)```

For classification, you can post-prune the tree, to result in fewer (hence larger) leaves:
```model = build_tree(labels, features)```
```pruned_model = prune_tree(model, leaf_purity)```

**Comment by veryluckyxyz** [comment]
Thank you!
