### ISSUE TITLE
Saving RandomForest Ensembles

### ISSUE THREAD

**Issue by marcstein** [bensadeghi/DecisionTree.jl#24]
In a production setting, I want to train a model with a fairly large dataset and then run classifications on a per line basis using a persistent model. Can I store the ensemble in a file (or redis) and then load it at runtime?

I've tried writing the resulting model to a file but the following approach:

outfile = open("model.txt", "w")
write(model,outfile)

fails with the following error:

ERROR: `write` has no method matching write(::Ensemble, ::IOStream) 

Any thoughts?

Thanks,

Marc

**Comment by bensadeghi** [comment]
To my knowledge, there is still no built-in variable writer, but you can use the [JLD.jl](https://github.com/JuliaLang/JLD.jl) package for this.
Just make sure to `using DecisionTree` before loading in the model/variable.

**Comment by marcstein** [comment]
Hi Ben,

Thanks for the response. I am now using JLD in the following manner.

model = build_forest(labels, features, 2, 10, 0.5)

jldopen("model.jld", "w") do file
    write(file, "model", model)
end

...

model = jldopen("model.jld", "r") do file
    read(file, "model")

outcome = apply_forest(model,
[2,659,0,1,3,1.57,88,0,0,2,2,15,10,0,0,2,26,26,3625,0,2,2,0,0,0,2,0,2,0,2,0,1,0,4,0,1,10,10,10,10])

But it seems like the structure of the variable 'model' is not being
maintained. How can I restore the structure to pass into 'apply_forest'?

Thanks,

Marc

**Comment by bensadeghi** [comment]
Are you loading/using the DT package before running jldopen()?

**Comment by bensadeghi** [comment]
Something like this:
```julia
using DecisionTree, JLD

n,m = 10^3, 5 ;
features = rand(n,m);
weights = rand(-1:1,m);
labels = _int(features * weights);
model = build_forest(labels, features, 2, 10)

jldopen("model.jld", "w") do file
    write(file, "model", model)
end
```
Exit Julia and jump back in
```julia
using DecisionTree, JLD

model = jldopen("model.jld", "r") do file
    read(file, "model") 
end

pred = apply_forest(model, [1,1,1,1,1])

print_tree(model.trees[1], 3)
```

**Comment by marcstein** [comment]
Here's the two scripts, build.jl and outcome.jl

#######

#build.jl

using DataFrames,DecisionTree, JLD

clarity = readtable("/Users/marcstein/Active/julia/clarity.csv");
head(clarity)

labels = array(clarity[:, 41]);
features = array(clarity[:, 1:40]);

n,m = 10^3, 5 ;
features = rand(n,m);
weights = rand(-1:1,m);
labels = _int(features * weights);
model = build_forest(labels, features, 2, 10)

jldopen("model.jld", "w") do file
    write(file, "model", model)
end


#outcome.jl

using DecisionTree, JLD

model = jldopen("model.jld", "r") do file
    read(file, "model")
end

pred = apply_forest(model,
[2,657,0,0,3,1.16,65,0,0,2,2,15,10,0,0,1,24,24,1500,0,1,1,0,0,0,1,0,2,0,1,0,1,0,2,0,1,13,13,13,13])
 #Good
# pred = apply_forest(model,
[2,839,1,0,1,1,56,0,0,5,2,15,10,0,0,1,48,60,3500,0,1,1,0,0,0,1,0,1,0,1,0,1,0,4,1,1,7,7,7,7])
#Bad

print_tree(model.trees[1], 3)

println(pred)

accuracy = nfoldCV_forest(labels, features, 2, 10, 3, 0.5)

score = (mean(accuracy[1:3]))

println(score)

#######

The pred for both Good and Bad tests is -1.

Both tests return

Feature 2, Threshold 0.4815685580156863

When I try to run nfoldCV_forest I get the error:

ERROR: labels not defined

I had thought that the structure of labels and features would be maintained
in the model. Is there another approach that I should use?

In my current model (in Ruby and Java) we pass in the vector and get back a
class prediction and confidence score. My hope was that Julia would allow
me to use the same language for the interface portion and the prediction
and would be faster than Java.

Any idea what my next step should be?

Thanks for the assistance!

Marc

**Comment by bensadeghi** [comment]
It looks like everything is working as it should.
The model generated, as a single tree or ensemble, does not "hold" the features or labels, but creates cascades of splits based on them. The print_tree() function can be used to display the structure of the tree.
If you want to run nfoldCV_forest(), then you should load in the labels and features. In fact, CV runs should be part of your build and testing stage, and once you're happy with the prediction results you're getting, then run build_forest() on the whole lot of data using the parameters tested with CV. You can then write that model to disk and fetch it later for making predictions.

**Comment by marcstein** [comment]
Thanks, I think I see the issue. I'm looking for a confidence value for
each prediction at runtime. I've been running 10 fold CV as part of the
build process, but I want the accuracy on a per prediction basis at run
time.
