### ISSUE TITLE
Error on @everywhere using DecisionTree

### ISSUE THREAD

**Issue by janvidpa** [bensadeghi/DecisionTree.jl#35]
I want to use DecisionTree across multiple processors.

Code:
_addprocs(3)
@everywhere using DecisionTree_

works fine on julia 3.11 pkg version-  0.3.11
I get the following error in julia 4.5 pkg version- 0.4.2
ERROR: On worker 2:
LoadError: UndefVarError: BaseClassifier not defined

**Comment by cstjean** [comment]
I could reproduce. I didn't have the problem if I imported/using'ed ScikitLearnBase explicitly.

```julia
addprocs(3)
@everywhere import ScikitLearnBase
@everywhere using DecisionTree
```

Let us know if that works for you too. I'm not familiar with Julia's multiprocessing facilities, so I don't know if that's a bug in Julia or in the DecisionTree codebase...

**Comment by janvidpa** [comment]
@cstjean This works for me. Not sure why we have to explicitly import ScikitLearnBase for all processors din't need to do so for other packages like Distributions.jl, StatsBase.jl

**Comment by cstjean** [comment]
Apparently it's a [known issue](https://github.com/JuliaLang/julia/issues/12381#issuecomment-126816290). We could fix it by importing ScikitLearnBase in DecisionTree.jl, but that's a bit ugly. The recommended fix is to write
```
addprocs(3)
import DecisionTree
@everywhere using DecisionTree
```
So I will close this for now.

**Comment by janvidpa** [comment]
Sure. Thanks!
