### ISSUE TITLE
Deprecated Dict comprehension warning

### ISSUE THREAD

**Issue by colbec** [bensadeghi/DecisionTree.jl#36]
Using Julia6 (but not Julia4) on `using DecisionTree` a warning appears (but code seems to run fine anyway):
```
WARNING: deprecated syntax "[a=>b for (a,b) in c]".
Use "Dict(a=>b for (a,b) in c)" instead.
```
This is the entire output, no indication of line numbers or affected files. Using:
```
Julia Version 0.6.0-dev.233
Commit 62615c3* (2016-08-16 05:34 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by cstjean** [comment]
Yes, that's deprecated syntax in Julia 0.5 and we need to `@compat` those lines. You can ignore the warnings for now.

**Comment by bensadeghi** [comment]
```@compat``` still does not support this automatic conversion.
We'll update DT.jl once Compat.jl has been brought up to speed.

**Comment by cstjean** [comment]
AFAICT it [cannot be done in compat.jl](https://github.com/JuliaLang/Compat.jl/issues/231), and we have to use `Dict([Pair(Symbol(k), v) for (k, v) in d])` to get rid of the warning.

**Comment by bensadeghi** [comment]
Great, thanks.

I'll go with ```Dict([Pair(v => k) for (k, v) in enumerate(labels)])```
