### ISSUE TITLE
"build_forest" does not accept categorical data?

### ISSUE THREAD

**Issue by sindhujapr** [bensadeghi/DecisionTree.jl#50]
My data can be described as follows:
features - Array{Any,2} - two columns of strings, and 3 columns containing numerical values
labels - Array{String,2} - array of strings

Now, when I use:

model = build_forest(labels, features, 2, 10, 0.5, 6)

I get:

MethodError: no method matching build_forest(::Array{String,2}, ::Array{Any,2}, ::Int64, ::Int64, ::Float64, ::Int64)

I get similar errors if I convert "features" and "labels" to categorical:
model = build_forest(categorical(labels), categorical(features), 2, 10, 0.5, 6)

It works when I use only the 3 numerical columns in the features array as features.

1. How do you build models using features that contain non-numeric data?
2. Am I using the "categorical" data incorrectly in the "build_forest" command?

For reference, the packages I am using in my code are:

using DecisionTree
using DataFrames
using CategoricalArrays

**Comment by bensadeghi** [comment]
I think your problem is with the dimensionality of your labels variable (Array{String,2}), which is currently a 2D array.
For build_forest(), the labels variable should be a Vector:
```
julia> Vector
Array{T,1} where T
```

You can convert the 2D array to a 1D array using reshape():
```
labels = reshape(labels, length(labels))
```
Let me know if this works for you.

**Comment by bensadeghi** [comment]
As long as each feature column is homogeneous (ie all type String), then it should work just fine:
 ```julia
features = ["yes" 4; "yes" 5; "no" 7]
labels = ["a", "a", "b"]
model = build_tree(labels, features)
print_tree(model)
```
If you have a heterogeneous column, then I'd recommend converting everything to String, ie:
```julia
features[:,2] = string.(features[:,2])
```
Give that a try

**Comment by sindhujapr** [comment]
My columns are homogeneous:

![image](https://user-images.githubusercontent.com/9027766/31830327-e1385078-b58d-11e7-8fe9-a38215bb1798.png)

Even still, I explicitly converted them to string, but got the same error:

model = build_forest(labels, features, 2, 10, 0.5, 6)


MethodError: no method matching build_forest(::Array{String,2}, ::Array{Any,2}, ::Int64, ::Int64, ::Float64, ::Int64)

**Comment by bensadeghi** [comment]
You need to convert the ```labels``` variable from a 2D array to a 1D array using reshape():
```julia
labels = reshape(labels, length(labels))
```

**Comment by sindhujapr** [comment]
We tried this in the beginning of the post. Initially, labels was a 25040x1 Array{String,2}
On reshaping using your command: it is 1D: String[25040]
Now, on trying to build the forest, I get the same error:


MethodError: no method matching DecisionTree.Node(::Int64, ::String, ::DecisionTree.Leaf{String}, ::DecisionTree.Node{String,Int64})
Closest candidates are:

**Comment by bensadeghi** [comment]
I've reverted to an older version of the ```Node``` type. This should resolve your problem.

Checkout the latest from master, and rerun your job
```Julia
Pkg.checkout("DecisionTree")
```

**Comment by sindhujapr** [comment]
Do I need to be on Julia 0.6.3 to be able to get this fix? I am currently on 0.6.1 and I get this warning when I try to checkout the latest:


INFO: Checking out DecisionTree master...
INFO: Pulling DecisionTree latest master...
WARNING: DecisionTree is fixed at 0.6.3+ conflicting with top-level requirement: [0.6.1,0.6.1+)
INFO: No packages to install, update or remove

**Comment by cstjean** [comment]
That's not referring to Julia; it refers to DecisionTree's version number. Do you have any package that depends on DecisionTree (via REQUIRE)?

**Comment by sindhujapr** [comment]
Not that I know of, the packages I am using are: DataFrames, Plots, StatsBase, CategoricalArrays and DecisionTree. None of them seem to directly depend on DecisionTree verison.

**Comment by cstjean** [comment]
What if you Pkg.free("DecisionTree") then checkout again? Also, what
does Pkg.dependents("DecisionTree") say?

**Comment by sindhujapr** [comment]
I still get the same warning, here are the outputs you requested:


INFO: Freeing DecisionTree
INFO: Downgrading DecisionTree: v0.6.3 => v0.6.1

Pkg.checkout("DecisionTree")
INFO: Checking out DecisionTree master...
INFO: Pulling DecisionTree latest master...
WARNING: DecisionTree is fixed at 0.6.3+ conflicting with top-level requirement: [0.6.1,0.6.1+)
INFO: No packages to install, update or remove

Pkg.dependents("DecisionTree")
AbstractString[2]
"Orchestra"
"GradientBoost"

**Comment by cstjean** [comment]
Well, it looks like you're on 0.6.3 anyway, regardless of the warning. Does
it solve your issue?

**Comment by sindhujapr** [comment]
Yes, it does! I am not able to use dataframes with strings in columns as input to "build_forest". Thank you bensadeghi and cstjean.
