### ISSUE TITLE
large memory footprint and slow performance on large datasets

### ISSUE THREAD

**Issue by Eight1911** [bensadeghi/DecisionTree.jl#59]
Due to the fact that the data matrix is being copied at every recursive call, the current implementation has a memory footprint that is unnecessarily large. This is a structural issue and may well require a complete rewrite of the `built_tree` function. For example, on my MBP, the @time macro prints the following when used on the build_tree function to split on the MNIST training dataset:

      2.866582 seconds (3.31 M allocations: 820.371 MiB, 3.99% gc time).

This above time does not include the JIT compile time. If the maintainer(s) gives me the green light, I will be making a couple of PR's in the upcoming weeks to fix this issue and hopefully up the performance of the current implementation. In particular, I will be making a small port of the sklearn trees [here](https://github.com/Eight1911/decision-trees/) compatible with the current API. The library linked has the following footprint

      0.496638 seconds (21.32 k allocations: 802.953 KiB, 1.00% gc time)

which is approximately a thousand times smaller with 5-6 times the performance and produces the same tree with the same number of nodes when asked to evaluate every feature for each split.

**Comment by bensadeghi** [comment]
Thanks for this @Eight1911.
Your contribution would be very welcome. Please do address the copyright issue about, and if possible, make it all compatible with Julia v0.7
