### ISSUE TITLE
DecisionTree v0.8.2 is not registered in the General registry

### ISSUE THREAD

**Issue by DilumAluthge** [bensadeghi/DecisionTree.jl#97]
If you look at the [list of DecisionTree releases](https://github.com/bensadeghi/DecisionTree.jl/releases), you'll see that the most recent release was `v0.8.2`, released on May 10, 2019.

However, if you look at the [General registry](https://github.com/JuliaRegistries/General/blob/master/D/DecisionTree/Versions.toml), the most recent release registered there was `v0.8.1`.

Could you register DecisionTree `v0.8.2` in the General registry?

**Comment by bensadeghi** [comment]
`v0.8.3` has been registered.
